name: ESLint Check

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: write

jobs: 
  lint-and-deploy:
    name: Run ESLint check and deploy Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup NodeJS for Build
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: install all Dependencies
        run: npm ci
        
      - name: Run ESLint test
        run: npm run lint:strict
        continue-on-error: true
        id: eslint

      - name: block PR if ESLint fails
        continue-on-error: true
        if: steps.eslint.outcome == 'failure'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: 'REQUEST_CHANGES',
              body: 'ESLint check failed. Please fix all linting issues (including warnings) before merging.'
            })

      - name: Run security audit
        run: npm audit
        continue-on-error: true
        id: security-audit

      - name: check for ESLint result
        if: steps.eslint.outcome == 'failure'
        run: |
          echo "ESLint found issues. Failing the workflow."
          exit 1
      
      - name: block PR if Security Check fails
        continue-on-error: true
        if: steps.security-audit.outcome == 'failure'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: 'REQUEST_CHANGES',
              body: 'Security check failed. Please fix all security warnings issues (including warnings) before merging.'
            })

      - name: build Project from React Files
        run: npm run build

      - name: create _redirects file
        run: echo "/healthcare/*    /index.html   200" > build/_redirects

      - name: deploy to netlify
        continue-on-error: true
        id: netlify-deploy
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './build'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}  # GITHUB_TOKEN and VAI throwing resource-inaccessible error
          deploy-message: "FROM GITHUB_ACTIONS"
          enable-pull-request-comment: true
          enable-commit-comment: false
          overwrites-pull-request-comment: false
          alias: healthcare-deploy-preview-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
